apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader
  namespace: formazione-sou
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-deployments-global
subjects:
- kind: ServiceAccount
  name: cluster-reader
  namespace: formazione-sou
roleRef:
  kind: ClusterRole
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io